python3 -m unittest .\geom2d\circle_test.py
python3 -m unittest .\geom2d\line_test.py
python3 -m unittest .\geom2d\open_interval_test.py
python3 -m unittest .\geom2d\point_test.py
python3 -m unittest .\geom2d\polygon_test.py
python3 -m unittest .\geom2d\rect_test.py
python3 -m unittest .\geom2d\segment_test.py
python3 -m unittest .\geom2d\vector_test.py
python3 -m unittest .\geom2d\affine_transf_test.py
